version: '3'

services:
  # Portainer service for Docker management
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - ptdata:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
   
  # CSV converter service
  csv-converter:
    build:
      context: ./Csvconverter/
      dockerfile: Dockerfile     
    depends_on:
      - db
    env_file: .env  
    ports:
      - 6037:6038
   

  # Nginx service for web server
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./ws/default.conf:/etc/nginx/conf.d/default.conf
      - ./ws/website:/var/www/html

  # PHP service for PHP application
  php:
    build:
      context: ./phpconf/
      dockerfile: Dockerfile
    volumes:
    - ./ws/website:/var/www/html

  # MySQL database service
  db:
    image: mysql:5.7
    container_name: db
    env_file: .env
    ports:
      - "6036:3306"  
    volumes:
      - ./dbdata:/var/lib/mysql
  

  # PhpMyAdmin service for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    env_file:
      - .env
    restart: always
    ports:
      - 8085:80
  

volumes:
  dbdata:  # Volume for MySQL data
  ptdata:  # Volume for Portainer data
