version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
        - ptdata:/data
        - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  csv-converter:
    build:
      context: ./Csvconverter
      dockerfile: Dockerfile
   
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: app_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    restart: always
    ports:
      - 6037:6038
    volumes: 
      - ./Csvconverter/data:/app/data
      
  web:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates

    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: app_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "6036:3306"  
    volumes:
      - ./dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8085:80

volumes:
  dbdata:
  csvconvdata:
  ptdata:
